### ISSUE TITLE
Cambio de 01/01/0001 en la marcacion de entrada o marcacion de salida.

### ISSUE THREAD

**Issue by Castachris** [nrubiano/Siciap.V1#5]
La idea es cambiar esa tipo de fecha por un texto que nos diga marcacion no valida o un mensaje que nos indique el suceso en el reporte de entrada y salidas del excel.

**Comment by nrubiano** [comment]
Solucionado en la 5.9

![image](https://cloud.githubusercontent.com/assets/17432958/13625331/a1e4316a-e584-11e5-8e2e-b6a316639078.png)
